/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Time */
        get: operations["get_time_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/situational_picture/{which}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Situational Picture */
        post: operations["get_situational_picture_situational_picture__which__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ground_truth/{which}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Ground Truth */
        post: operations["get_ground_truth_ground_truth__which__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculate_monostatic_coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Line Of Sight */
        post: operations["calculate_line_of_sight_calculate_monostatic_coverage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculate_min_detectable_rcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Min Detectable Rcs
         * @description Calculate the minimum detectable radar cross section for the given
         *     sensor on a grid. The grid dimensions are (lat, lon, MASL).
         *
         *     The value -1 indicates a NaN, i. e. the sensor cannot detect a target
         *     at all at that position.
         */
        post: operations["calculate_min_detectable_rcs_calculate_min_detectable_rcs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculate_pcl_coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Pcl Coverage
         * @description Calculate PCL coverage.
         *
         *     Parameters
         *     ----------
         *     sensors: list[PclSensor]
         *         Sensors
         *     grid: LatLonHeightGrid
         *         Calculation grid
         *     rcs: float
         *         Radar cross section for which to calculate the coverage
         *     snr_threshold: float, default theia.config.SNR_THRESHOLD_PCL
         *         Minimum detectable threshold [dB]
         *     doppler_threshold: float, default theia.config.DOPPLER_SHIFT_THRESHOLD_PCL
         *         Minimum detectable Doppler shift [Hz]
         *     delay_threshold: float, default theia.config.DELAY_THRESHOLD_PCL
         *         Delay threshold for PCL [us].
         *         This is used to judge whether a given transmitter - target - receiver geometry
         *         is in the bistatic or the forward scattering regime.
         *
         *     Returns
         *     -------
         *     track_init_coverage: GeoJSONFeature
         *         Region in which a track init can happen only using PCL
         *     track_update_coverage: GeoJSONFeature
         *         Region in which a track update can happen only using PCL
         */
        post: operations["calculate_pcl_coverage_calculate_pcl_coverage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Health */
        get: operations["check_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/is_paused": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Paused */
        get: operations["is_paused_is_paused_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speedup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Speedup Factor */
        get: operations["get_speedup_factor_speedup_get"];
        put?: never;
        /** Set Speedup Factor */
        post: operations["set_speedup_factor_speedup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geojson/{which}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Geojson */
        get: operations["get_geojson_geojson__which__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/elevation_at/{lat}_{lon}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Elevationat
         * @description Calculate elevation [MASL] for the given decimal (lat, lon) coordinates.
         */
        get: operations["elevationAt_elevation_at__lat___lon__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fm_transmitters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fm Transmitters */
        get: operations["get_fm_transmitters_fm_transmitters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line_of_sight_distance/{lat1}_{lon1}_{alt1}/{lat2}_{lon2}_{alt2}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Los Distance
         * @description Calculate LOS distance [m]
         */
        get: operations["get_los_distance_line_of_sight_distance__lat1___lon1___alt1___lat2___lon2___alt2__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/haversine_distance/{lat1}_{lon1}/{lat2}_{lon2}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Haversine Distance */
        get: operations["get_haversine_distance_haversine_distance__lat1___lon1___lat2___lon2__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terrain_models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Terrain Models */
        get: operations["get_terrain_models_terrain_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttenuationModel
         * @description Representation of an antenna attenuation diagram.
         *
         *     Actually represents the squared attenuation coefficients :math:`F_t, F_r`.
         */
        AttenuationModel: {
            /** Attenuation Table Angles */
            attenuation_table_angles: number[];
            /** Attenuation Table Values */
            attenuation_table_values: number[];
            polarization: components["schemas"]["Polarization"];
        };
        /** Body_calculate_min_detectable_rcs_calculate_min_detectable_rcs_post */
        Body_calculate_min_detectable_rcs_calculate_min_detectable_rcs_post: {
            sensor: components["schemas"]["PclSensor-Input"];
            grid: components["schemas"]["LatLonHeightGrid"];
        };
        /** Body_calculate_pcl_coverage_calculate_pcl_coverage_post */
        Body_calculate_pcl_coverage_calculate_pcl_coverage_post: {
            /** Sensors */
            sensors: components["schemas"]["PclSensor-Input"][];
            grid: components["schemas"]["LatLonHeightGrid"];
        };
        /** ConstantRcsModel */
        ConstantRcsModel: {
            /** Rcs */
            rcs: number;
        };
        /** EventMessage */
        EventMessage: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Msg */
            msg: string;
        };
        /** ExtrapolatedGroundtruth */
        ExtrapolatedGroundtruth: {
            /** Target Id */
            target_id: number;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
            /** Sidc */
            sidc: string;
        };
        /** ExtrapolatedSituationalPicture */
        ExtrapolatedSituationalPicture: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Friendly Radars */
            friendly_radars: (components["schemas"]["MonostaticSensor-Output"] | components["schemas"]["PclSensor-Output"] | components["schemas"]["PetSensor"] | components["schemas"]["VisualSensor"])[];
            /** Enemy Tracks */
            enemy_tracks: components["schemas"]["ExtrapolatedTrack"][];
        };
        /** ExtrapolatedTrack */
        ExtrapolatedTrack: {
            /** Id */
            id: string;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
            /** Sidc */
            sidc: string;
            receiver?: components["schemas"]["Receiver-Output"] | null;
            transmitter?: components["schemas"]["Transmitter-Output"] | null;
        };
        /** GeoJSONFeature */
        GeoJSONFeature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry: components["schemas"]["GeoJSONPolygon"] | components["schemas"]["GeoJSONMultiPolygon"];
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
        };
        /** GeoJSONMultiPolygon */
        GeoJSONMultiPolygon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: number[][][][];
        };
        /** GeoJSONPolygon */
        GeoJSONPolygon: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: number[][][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatLonHeightGrid */
        LatLonHeightGrid: {
            /** Lat Start */
            lat_start: number;
            /** Lat Stop */
            lat_stop: number;
            /** Lat Res */
            lat_res: number;
            /** Lon Start */
            lon_start: number;
            /** Lon Stop */
            lon_stop: number;
            /** Lon Res */
            lon_res: number;
            /** Height Start */
            height_start: number;
            /** Height Stop */
            height_stop: number;
            /** Height Res */
            height_res: number;
        };
        /** MonostaticRadarMeasurementModel */
        MonostaticRadarMeasurementModel: {
            /**
             * Min Range Uncertainty
             * @default 100
             */
            min_range_uncertainty: number;
            /**
             * Max Range Uncertainty
             * @default 10000
             */
            max_range_uncertainty: number;
            /**
             * Min Angular Uncertainty
             * @default 0.017453292519943295
             */
            min_angular_uncertainty: number;
            /**
             * Max Angular Uncertainty
             * @default 6.283185307179586
             */
            max_angular_uncertainty: number;
        };
        /** MonostaticSensor */
        "MonostaticSensor-Input": {
            /** Id */
            id: number;
            transmitter: components["schemas"]["Transmitter-Input"];
            receiver: components["schemas"]["Receiver-Input"];
            error_model: components["schemas"]["MonostaticRadarMeasurementModel"];
        };
        /** MonostaticSensor */
        "MonostaticSensor-Output": {
            /** Id */
            id: number;
            transmitter: components["schemas"]["Transmitter-Output"];
            receiver: components["schemas"]["Receiver-Output"];
            error_model: components["schemas"]["MonostaticRadarMeasurementModel"];
        };
        /**
         * PclMeasurementModel
         * @description Measurement model for PCL detections.
         *
         *     This model implements the Cramér-Rao Bound (CRB) of the uncertainty.
         *
         *     Notes
         *     -----
         *     This class implements Equ. (22) of the following article:
         *     A. Quazi, "An overview on the time delay estimate in active and passive
         *     systems for target localization,"
         *     in IEEE Transactions on Acoustics, Speech, and Signal Processing,
         *     vol. 29, no. 3, pp. 527-533, June 1981, doi: 10.1109/TASSP.1981.1163618.
         */
        PclMeasurementModel: {
            /**
             * Min Bistatic Range Uncertainty
             * @default 0
             */
            min_bistatic_range_uncertainty: number;
            /**
             * Max Bistatic Range Uncertainty
             * @default 10000
             */
            max_bistatic_range_uncertainty: number;
            /**
             * Min Doppler Uncertainty
             * @default 0
             */
            min_doppler_uncertainty: number;
            /**
             * Max Doppler Uncertainty
             * @default 10000
             */
            max_doppler_uncertainty: number;
        };
        /** PclSensor */
        "PclSensor-Input": {
            /** Id */
            id: number;
            transmitter: components["schemas"]["Transmitter-Input"];
            receiver: components["schemas"]["Receiver-Input"];
            error_model: components["schemas"]["PclMeasurementModel"];
        };
        /** PclSensor */
        "PclSensor-Output": {
            /** Id */
            id: number;
            transmitter: components["schemas"]["Transmitter-Output"];
            receiver: components["schemas"]["Receiver-Output"];
            error_model: components["schemas"]["PclMeasurementModel"];
        };
        /** PetMeasurementModel */
        PetMeasurementModel: {
            /**
             * Min Elevation Uncertainty
             * @default 0.017453292519943295
             */
            min_elevation_uncertainty: number;
            /**
             * Max Elevation Uncertainty
             * @default 0.17453292519943295
             */
            max_elevation_uncertainty: number;
            /**
             * Min Azimuth Uncertainty
             * @default 0.017453292519943295
             */
            min_azimuth_uncertainty: number;
            /**
             * Max Azimuth Uncertainty
             * @default 0.17453292519943295
             */
            max_azimuth_uncertainty: number;
        };
        /** PetSensor */
        PetSensor: {
            /** Id */
            id: number;
            transmitter: components["schemas"]["Transmitter-Output"];
            receiver: components["schemas"]["Receiver-Output"];
            target: components["schemas"]["Target"];
            error_model: components["schemas"]["PetMeasurementModel"];
        };
        /** Point */
        Point: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt */
            alt: number;
        };
        /**
         * Polarization
         * @enum {integer}
         */
        Polarization: 0 | 1;
        /** Receiver */
        "Receiver-Input": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Antenna Height */
            antenna_height: number;
            /** Diameter */
            diameter: number;
            /** Cpi Pulses */
            cpi_pulses: number;
            /** Pfa */
            pfa: number;
            /** Min Elevation */
            min_elevation: number;
            /** Max Elevation */
            max_elevation: number;
            /** Min Azimuth */
            min_azimuth: number;
            /** Max Azimuth */
            max_azimuth: number;
            /** Rotation Time */
            rotation_time: number;
            /** Bandwidth */
            bandwidth: number;
            /**
             * Gain
             * @default 0
             */
            gain: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Noise Temperature
             * @default 300
             */
            noise_temperature: number;
            /**
             * Noise Figure
             * @default 1.9
             */
            noise_figure: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /** Receiver */
        "Receiver-Output": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Antenna Height */
            antenna_height: number;
            /** Diameter */
            diameter: number;
            /** Cpi Pulses */
            cpi_pulses: number;
            /** Pfa */
            pfa: number;
            /** Min Elevation */
            min_elevation: number;
            /** Max Elevation */
            max_elevation: number;
            /** Min Azimuth */
            min_azimuth: number;
            /** Max Azimuth */
            max_azimuth: number;
            /** Rotation Time */
            rotation_time: number;
            /** Bandwidth */
            bandwidth: number;
            /**
             * Gain
             * @default 0
             */
            gain: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Noise Temperature
             * @default 300
             */
            noise_temperature: number;
            /**
             * Noise Figure
             * @default 1.9
             */
            noise_figure: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /**
         * Target
         * @description Represents a detectable entity.
         */
        Target: {
            /** Id */
            id: number;
            /** Is Stationary */
            is_stationary: boolean;
            /**
             * Name
             * @default
             */
            name: string;
            /** Sidc */
            sidc: string;
            point: components["schemas"]["Point"];
            cross_section_model: components["schemas"]["ConstantRcsModel"];
            velocity: components["schemas"]["Velocity"];
            receiver?: components["schemas"]["Receiver-Output"] | null;
            transmitter?: components["schemas"]["Transmitter-Output"] | null;
        };
        /**
         * Team
         * @enum {string}
         */
        Team: "BLUE" | "RED";
        /** TrackPoint */
        TrackPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt */
            alt: number;
            /** V East */
            v_east: number;
            /** V North */
            v_north: number;
            /** V Up */
            v_up: number;
        };
        /** Transmitter */
        "Transmitter-Input": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Power */
            power: number;
            /** Erp */
            erp: number;
            /** Antenna Height */
            antenna_height: number;
            /** Antenna Diameter */
            antenna_diameter: number;
            /** Antenna Gain */
            antenna_gain: number;
            /** Frequency */
            frequency: number;
            /** Pulse Width */
            pulse_width: number;
            polarization: components["schemas"]["Polarization"];
            /** Bandwidth */
            bandwidth: number;
            /**
             * Max Coherent Integration Time
             * @default 0.5
             */
            max_coherent_integration_time: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /** Transmitter */
        "Transmitter-Output": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Power */
            power: number;
            /** Erp */
            erp: number;
            /** Antenna Height */
            antenna_height: number;
            /** Antenna Diameter */
            antenna_diameter: number;
            /** Antenna Gain */
            antenna_gain: number;
            /** Frequency */
            frequency: number;
            /** Pulse Width */
            pulse_width: number;
            polarization: components["schemas"]["Polarization"];
            /** Bandwidth */
            bandwidth: number;
            /**
             * Max Coherent Integration Time
             * @default 0.5
             */
            max_coherent_integration_time: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Velocity */
        Velocity: {
            /** Vx */
            vx: number;
            /** Vy */
            vy: number;
            /** Vz */
            vz: number;
        };
        /** VisualSensor */
        VisualSensor: {
            /** Id */
            id: number;
            /**
             * @default {
             *       "id": -1,
             *       "point": {
             *         "alt": 0,
             *         "lat": 0,
             *         "lon": 0
             *       },
             *       "power": 0,
             *       "antenna_height": 0,
             *       "antenna_diameter": 0,
             *       "antenna_gain": 0,
             *       "frequency": 0,
             *       "pulse_width": 0,
             *       "polarization": 0,
             *       "bandwidth": 0,
             *       "max_coherent_integration_time": 0,
             *       "antenna_efficiency_value": 0
             *     }
             */
            transmitter: components["schemas"]["Transmitter-Output"];
            receiver: components["schemas"]["Receiver-Output"];
            /** Detection Range */
            detection_range: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_time_time_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_situational_picture_situational_picture__which__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                which: components["schemas"]["Team"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrapolatedSituationalPicture"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ground_truth_ground_truth__which__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                which: components["schemas"]["Team"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrapolatedGroundtruth"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_line_of_sight_calculate_monostatic_coverage_post: {
        parameters: {
            query: {
                target_alt: number;
                max_range: number;
                azimuth_resolution_degree: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Point"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_min_detectable_rcs_calculate_min_detectable_rcs_post: {
        parameters: {
            query?: {
                snr_threshold?: number;
                doppler_threshold?: number;
                delay_threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_calculate_min_detectable_rcs_calculate_min_detectable_rcs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[][][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_pcl_coverage_calculate_pcl_coverage_post: {
        parameters: {
            query: {
                rcs: number;
                snr_threshold?: number;
                doppler_threshold?: number;
                delay_threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_calculate_pcl_coverage_calculate_pcl_coverage_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": [
                        components["schemas"]["GeoJSONFeature"],
                        components["schemas"]["GeoJSONFeature"]
                    ];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    pause_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    resume_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    is_paused_is_paused_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    get_speedup_factor_speedup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    set_speedup_factor_speedup_post: {
        parameters: {
            query: {
                speedup_factor: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_events_get: {
        parameters: {
            query?: {
                t_start?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geojson_geojson__which__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                which: components["schemas"]["Team"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["GeoJSONFeature"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elevationAt_elevation_at__lat___lon__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lat: number;
                lon: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fm_transmitters_fm_transmitters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transmitter-Output"][];
                };
            };
        };
    };
    get_los_distance_line_of_sight_distance__lat1___lon1___alt1___lat2___lon2___alt2__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lat1: number;
                lon1: number;
                alt1: number;
                lat2: number;
                lon2: number;
                alt2: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_haversine_distance_haversine_distance__lat1___lon1___lat2___lon2__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lat1: number;
                lon1: number;
                lat2: number;
                lon2: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_terrain_models_terrain_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
